name: Docker Image CI
env:
  DOCKERHUB_REGISTRY: docker.io/swetank01
  DOCKERHUB_REGISTRY_USER: swetank01
  DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: "angular"
  TAG: "master"

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "update" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd angular
        docker build . --file Dockerfile --tag $DOCKERHUB_REGISTRY/$DOCKERHUB_REGISTRY_USER:$TAG
        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_REGISTRY_USER }}
        password: ${{ env.DOCKERHUB_REGISTRY_PASSWORD }}
    
    - name: Docker Push
      run: docker push $IMAGE_REGISTRY_USER/$APP_NAME:$IMAGE_TAGS
